screen_w = 1280
screen_h = 720
x_fields = 16
y_fields = 9
rot = math.pi / 2
shield_size = 1 / 2 * math.pi
fire_sprite_max = 6
fire_sprite_max = 10
fire_time = 300
item_spawn_rate = 600
game_victory = 0
auto_reload = 1
music_volume = 0
sound_volume = 0.5
fullscreen = false
launch_on_menu = 0